// Generated by gencpp from file controller/motorpos.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_MOTORPOS_H
#define CONTROLLER_MESSAGE_MOTORPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct motorpos_
{
  typedef motorpos_<ContainerAllocator> Type;

  motorpos_()
    : angular(0)  {
    }
  motorpos_(const ContainerAllocator& _alloc)
    : angular(0)  {
  (void)_alloc;
    }



   typedef uint16_t _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::controller::motorpos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::motorpos_<ContainerAllocator> const> ConstPtr;

}; // struct motorpos_

typedef ::controller::motorpos_<std::allocator<void> > motorpos;

typedef boost::shared_ptr< ::controller::motorpos > motorposPtr;
typedef boost::shared_ptr< ::controller::motorpos const> motorposConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::motorpos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::motorpos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'controller': ['/root/catkin_ws/src/controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controller::motorpos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::motorpos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::motorpos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::motorpos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::motorpos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::motorpos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::motorpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "620daad8e7540d60806fb147811e141d";
  }

  static const char* value(const ::controller::motorpos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x620daad8e7540d60ULL;
  static const uint64_t static_value2 = 0x806fb147811e141dULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::motorpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/motorpos";
  }

  static const char* value(const ::controller::motorpos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::motorpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 angular\n\
";
  }

  static const char* value(const ::controller::motorpos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::motorpos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorpos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::motorpos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::motorpos_<ContainerAllocator>& v)
  {
    s << indent << "angular: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_MOTORPOS_H
