// Generated by gencpp from file controller/setpos.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_SETPOS_H
#define CONTROLLER_MESSAGE_SETPOS_H

#include <ros/service_traits.h>


#include <controller/setposRequest.h>
#include <controller/setposResponse.h>


namespace controller
{

struct setpos
{

typedef setposRequest Request;
typedef setposResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setpos
} // namespace controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller::setpos > {
  static const char* value()
  {
    return "b7d0a4a753fe0e11a1400076e4574484";
  }

  static const char* value(const ::controller::setpos&) { return value(); }
};

template<>
struct DataType< ::controller::setpos > {
  static const char* value()
  {
    return "controller/setpos";
  }

  static const char* value(const ::controller::setpos&) { return value(); }
};


// service_traits::MD5Sum< ::controller::setposRequest> should match 
// service_traits::MD5Sum< ::controller::setpos > 
template<>
struct MD5Sum< ::controller::setposRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller::setpos >::value();
  }
  static const char* value(const ::controller::setposRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::setposRequest> should match 
// service_traits::DataType< ::controller::setpos > 
template<>
struct DataType< ::controller::setposRequest>
{
  static const char* value()
  {
    return DataType< ::controller::setpos >::value();
  }
  static const char* value(const ::controller::setposRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller::setposResponse> should match 
// service_traits::MD5Sum< ::controller::setpos > 
template<>
struct MD5Sum< ::controller::setposResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller::setpos >::value();
  }
  static const char* value(const ::controller::setposResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::setposResponse> should match 
// service_traits::DataType< ::controller::setpos > 
template<>
struct DataType< ::controller::setposResponse>
{
  static const char* value()
  {
    return DataType< ::controller::setpos >::value();
  }
  static const char* value(const ::controller::setposResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MESSAGE_SETPOS_H
