// Generated by gencpp from file controller/setposRequest.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_SETPOSREQUEST_H
#define CONTROLLER_MESSAGE_SETPOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct setposRequest_
{
  typedef setposRequest_<ContainerAllocator> Type;

  setposRequest_()
    : cmd(0)  {
    }
  setposRequest_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef uint16_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::controller::setposRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::setposRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setposRequest_

typedef ::controller::setposRequest_<std::allocator<void> > setposRequest;

typedef boost::shared_ptr< ::controller::setposRequest > setposRequestPtr;
typedef boost::shared_ptr< ::controller::setposRequest const> setposRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::setposRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::setposRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'controller': ['/root/catkin_ws/src/controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controller::setposRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::setposRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::setposRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::setposRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::setposRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::setposRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::setposRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e923d8b5bede2be04b562e0f28dfb89";
  }

  static const char* value(const ::controller::setposRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e923d8b5bede2beULL;
  static const uint64_t static_value2 = 0x04b562e0f28dfb89ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::setposRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/setposRequest";
  }

  static const char* value(const ::controller::setposRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::setposRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 cmd\n\
";
  }

  static const char* value(const ::controller::setposRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::setposRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setposRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::setposRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::setposRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_SETPOSREQUEST_H
