(cl:in-package controller-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          RX-VAL
          RX
          RY-VAL
          RY
          RZ-VAL
          RZ
          J1-VAL
          J1
          J2-VAL
          J2
          J3-VAL
          J3
          J4-VAL
          J4
          J5-VAL
          J5
          J6-VAL
          J6
          SELECT_MODE-VAL
          SELECT_MODE
          START-VAL
          START
          FORWARD_BACK-VAL
          FORWARD_BACK
          GEAR-VAL
          GEAR
          RS_BUTTON-VAL
          RS_BUTTON
          MD_DS_BUTTON-VAL
          MD_DS_BUTTON
          RC_EN_BUTTON-VAL
          RC_EN_BUTTON
          START_STOP-VAL
          START_STOP
))